const BooksApi = [{
id:1,
image:"images/kite.jpg",
price:554,
name:"The Kite Runner",
Genre:"Fiction",
Description:"The Kite Runner is the first novel by Afghan-American author Khaled Hosseini. Published in 2003 by Riverhead Books, it tells the story of Amir, a young boy from the Wazir Akbar Khan district of Kabul.",
amount : 1,
},
{
    id:2,
    image:"images/greatgatsby.jpg",
    price: 600,
    name:"The Great Gatsby",
    Genre:"Fiction",
    Description:"The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, near New York City, the novel depicts first-person narrator Nick Carraway's interactions with mysterious millionaire Jay Gatsby and Gatsby's obsession to reunite with his former lover, Daisy Buchanan.",
    amount : 1,    
},
    {
        id:3,
        image:"images/guest.jpeg",
        price:470,
        name:"The Guest List",
        Genre:"Thriller",
        Description:"*The brand new thriller from Lucy Foley – THE PARIS APARTMENT – is available to pre-order now* The No.1 Sunday Times bestseller *Over 1 million copies sold worldwide* *One of The Times and Sunday ...",
        amount : 1,
    },
        {
            id:4,
            image:"images/train.jpeg",
            price:650,
            name:"The Girl on The Train",
            Genre:"Thriller",
            Description:"The Girl on the Train is a 2015 psychological thriller novel by British author Paula Hawkins that gives narratives from three different women about relationship troubles and, for the main protagonist, alcoholism.",
            amount : 1,   
        },
            {
                id:5,
                image:"images/java.jpg",
                price:500,
                name:"Java: The Complete Reference",
                Genre:"Tech",
                Description:" step-by-step guide by the famous computing author Herbert Schildt, Java: The Complete Reference, Seventh Edition is an introductory book to Java. Whether a person is a rookie or a pro programmer, this book is for everyone. Introducing the readers to Java from the scratch to its importance and contribution to the web, the book has it all. The book is a gateway to the entire Java language, which includes steps required to learn Java in the easiest way.",
                amount : 1,    
            },  
                {
                    id:6,
                    image:"images/c__.jpg",
                    price:700,
                    name:"Beginning C++ Programming",
                    Genre:"Tech",
                    Description:"Modern C++ at your fingertips! About This Book * This book gets you started with the exciting world of C++ programming * It will enable you to write C++ code that uses the standard library, has a level of object orientation, and uses memory in a safe and effective way * It forms the basis of programming and covers concepts such as data structures and the core programming language Who This Book Is For A computer, an internet connection, and the desire to learn how to code in C++ is all you need to get started with this book.",
                    amount : 1,
                }, 
                    {
                        id:7,
                        image:"images/notebook.jpeg",
                        price:400,
                        name:"The Notebook",
                        Genre:"Romance",
                        Description:"The Notebook is a 1996 romantic novel by American novelist Nicholas Sparks. The novel was later adapted into a popular 2004 film of the same name.",
                        amount : 1,
                    },   
                        {
                            id:8,
                            image:"images/ends.jpeg",
                            price:800,
                            name:"It Ends with US",
                            Genre:"Romance",
                            Description:`It Ends with Us is a romance novel by Colleen Hoover, published by Atria Books on August 2, 2016. It is based on the relationship between Hoover's mother and father. Hoover described it in 2016 as "the hardest book I have ever written."`,
                            amount : 1,    
                        }, 
                            {
                                id:9,
                                image:"images/good evil.jpeg",
                                price:300,
                                name:"Beyond Good and Evil",
                                Genre:"Philosophy",
                                Description:"Beyond Good and Evil: Prelude to a Philosophy of the Future is a book by philosopher Friedrich Nietzsche that covers ideas in his previous work Thus Spoke Zarathustra but with a more polemical approach. It was first published in 1886 under the publishing house C. G",
                                amount : 1,    
                            },    
                                {
                                    id:10,
                                    image:"images/anathem.jpeg",
                                    price:700,
                                    name:"Anathem",
                                    Genre:"Philosophy",
                                    Description:"Anathem is a science fiction novel by American writer Neal Stephenson, published in 2008. Major themes include the many-worlds interpretation of quantum mechanics and the philosophical debate between Platonic realism and nominalism",
                                    amount : 1,
                                },
];
 export default BooksApi;